"""empty message

Revision ID: 710a67c470e3
Revises: d4af986e051d
Create Date: 2020-03-08 15:18:12.071709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710a67c470e3'
down_revision = 'd4af986e051d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_categories',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='cascade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_categories')
    # ### end Alembic commands ###
