"""empty message

Revision ID: ee64ff65b88a
Revises: 8fb338495dba
Create Date: 2020-02-27 21:36:05.061047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee64ff65b88a'
down_revision = '8fb338495dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(length=128), nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
